# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ll_Rcpp <- function(allprobs, gamma, delta, nSteps) {
    .Call(`_HMMiSSA_ll_Rcpp`, allprobs, gamma, delta, nSteps)
}

